name: i_called
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  zego_uikit_prebuilt_call: ^3.15.3
  flutter_svg: ^2.0.7
  zego_uikit_signaling_plugin: ^2.5.2
  firebase_core: ^2.17.0
  firebase_auth: ^4.10.1
  equatable: ^2.0.5
  fpdart: ^1.1.0
  provider: ^6.0.5
  cloud_firestore: ^4.9.3
  get_it: ^7.6.4
  zego_uikit_prebuilt_video_conference: ^2.6.1
  lottie: ^2.6.0

dependency_overrides:
  awesome_notifications: ^0.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/
